// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnofdwklnhbayfcxxbrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBub2Zkd2tsbmhiYXlmY3h4YnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxMjM5MzUsImV4cCI6MjA5OTY5OTkzNX0.m6Jy05h3CsETfpCyvcrOOm3XonaWlAJPaD5t6_Mk3NQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});